// ============================================
// COMPLETE URDU CORPUS - 5000+ WORDS
// Covers: Poetry, Prose, Religious, Karbala, Ghalib, Iqbal, Faiz, Everyday
// ============================================

export const urduCorpus = {
  // ============================================
  // PRONOUNS (ضمائر)
  // ============================================
  'میں': 'main',
  'ہم': 'hum',
  'تو': 'tu',
  'تم': 'tum',
  'آپ': 'aap',
  'وہ': 'woh',
  'یہ': 'yeh',
  'اُس': 'us',
  'اِس': 'is',
  'اُن': 'un',
  'اِن': 'in',
  'اُس نے': 'usne',
  'اِس نے': 'isne',
  'اُنہوں نے': 'unhon ne',
  'اِنہوں نے': 'inhon ne',
  'مجھے': 'mujhe',
  'تجھے': 'tujhe',
  'آپ کو': 'aap ko',
  'ہمیں': 'humein',
  'تمہیں': 'tumhein',
  'اُنہیں': 'unhein',
  'اِنہیں': 'inhein',
  'میرا': 'mera',
  'میری': 'meri',
  'میرے': 'mere',
  'تیرا': 'tera',
  'تیری': 'teri',
  'تیرے': 'tere',
  'ہمارا': 'hamara',
  'ہماری': 'hamari',
  'ہمارے': 'hamare',
  'تمہارا': 'tumhara',
  'تمہاری': 'tumhari',
  'تمہارے': 'tumhare',
  'آپ کا': 'aap ka',
  'آپ کی': 'aap ki',
  'آپ کے': 'aap ke',
  'اُس کا': 'us ka',
  'اُس کی': 'us ki',
  'اُس کے': 'us ke',
  'اِن کا': 'in ka',
  'اِن کی': 'in ki',
  'اِن کے': 'in ke',
  'اُن کا': 'un ka',
  'اُن کی': 'un ki',
  'اُن کے': 'un ke',

  // ============================================
  // VERBS - Present Tense (افعال - حال)
  // ============================================
  'کرتا': 'karta',
  'کرتی': 'karti',
  'کرتے': 'karte',
  'کرنا': 'karna',
  'کر رہا': 'kar raha',
  'کر رہی': 'kar rahi',
  'کر رہے': 'kar rahe',
  'کر چکا': 'kar chuka',
  'کر چکی': 'kar chuki',
  'کر چکے': 'kar chuke',
  
  'جانا': 'jana',
  'جاتا': 'jata',
  'جاتی': 'jati',
  'جاتے': 'jate',
  'جا رہا': 'ja raha',
  'جا رہی': 'ja rahi',
  'جا رہے': 'ja rahe',
  'جا چکا': 'ja chuka',
  
  'آنا': 'aana',
  'آتا': 'aata',
  'آتی': 'aati',
  'آتے': 'aate',
  'آ رہا': 'aa raha',
  'آ رہی': 'aa rahi',
  'آ رہے': 'aa rahe',
  
  'رہنا': 'rehna',
  'رہتا': 'rehta',
  'رہتی': 'rehti',
  'رہتے': 'rehte',
  'رہ رہا': 'reh raha',
  
  'دیکھنا': 'dekhna',
  'دیکھتا': 'dekhta',
  'دیکھتی': 'dekhti',
  'دیکھتے': 'dekhte',
  'دیکھ رہا': 'dekh raha',
  'دیکھ رہی': 'dekh rahi',
  'دیکھ رہے': 'dekh rahe',
  
  'بولنا': 'bolna',
  'بولتا': 'bolta',
  'بولتی': 'bolti',
  'بولتے': 'bolte',
  
  'سننا': 'sanna',
  'سنتا': 'sunta',
  'سنتی': 'sunti',
  'سنتے': 'sunte',
  
  'پڑھنا': 'parhna',
  'پڑھتا': 'parhta',
  'پڑھتی': 'parhti',
  'پڑھتے': 'parhte',
  
  'لکھنا': 'likhna',
  'لکھتا': 'likhta',
  'لکھتی': 'likhti',
  'لکھتے': 'likhte',
  
  'کھانا': 'khana',
  'کھاتا': 'khata',
  'کھاتی': 'khati',
  'کھاتے': 'khate',
  
  'پینا': 'peena',
  'پیتا': 'peeta',
  'پیتی': 'peeti',
  'پیتے': 'peete',
  
  'سونا': 'sona',
  'سوتا': 'sota',
  'سوتی': 'soti',
  'سوتے': 'sote',
  
  'اٹھنا': 'uthna',
  'اٹھتا': 'uthhta',
  'اٹھتی': 'uthhti',
  'اٹھتے': 'uthhte',
  
  'بیٹھنا': 'baithna',
  'بیٹھتا': 'baithta',
  'بیٹھتی': 'baithti',
  'بیٹھتے': 'baithte',
  
  'چلنا': 'chalna',
  'چلتا': 'chalta',
  'چلتی': 'chalti',
  'چلتے': 'chalte',
  
  'دوڑنا': 'dorna',
  'دوڑتا': 'dorta',
  'دوڑتی': 'dorti',
  'دوڑتے': 'dorte',
  
  'ہنسنا': 'hansna',
  'ہنستا': 'hansta',
  'ہنستی': 'hansti',
  'ہنستے': 'hanste',
  
  'رونا': 'rona',
  'روتا': 'rota',
  'روتی': 'roti',
  'روتے': 'rote',
  
  'ماننا': 'manna',
  'مانتا': 'manta',
  'مانتی': 'manti',
  'مانتے': 'mante',

  // ============================================
  // VERBS - Past Tense (افعال - ماضی)
  // ============================================
  'کیا': 'kiya',
  'کی': 'ki',
  'کئے': 'kiye',
  'کیا تھا': 'kiya tha',
  'کی تھی': 'ki thi',
  'کئے تھے': 'kiye the',
  
  'گیا': 'gaya',
  'گئی': 'gayi',
  'گئے': 'gaye',
  'گیا تھا': 'gaya tha',
  'گئی تھی': 'gayi thi',
  'گئے تھے': 'gaye the',
  
  'آیا': 'aaya',
  'آئی': 'aai',
  'آئے': 'aaye',
  
  'دیا': 'diya',
  'دی': 'di',
  'دئے': 'diye',
  
  'لیا': 'liya',
  'لی': 'li',
  'لئے': 'liye',
  
  'کہا': 'kaha',
  'کہی': 'kahi',
  'کہے': 'kahe',
  
  'سنا': 'suna',
  'سنی': 'suni',
  'سنے': 'sune',
  
  'پڑھا': 'parha',
  'پڑھی': 'parhi',
  'پڑھے': 'parhe',
  
  'لکھا': 'likha',
  'لکھی': 'likhi',
  'لکھے': 'likhe',

  // ============================================
  // VERBS - Future Tense (افعال - مستقبل)
  // ============================================
  'کرے گا': 'karega',
  'کرے گی': 'karegi',
  'کریں گے': 'kareinge',
  'کرے': 'kare',
  
  'جائے گا': 'jaega',
  'جائے گی': 'jaegi',
  'جائیں گے': 'jaeinge',
  
  'آئے گا': 'aega',
  'آئے گی': 'aegi',
  'آئیں گے': 'aeinge',
  
  'دیکھے گا': 'dekhega',
  'دیکھے گی': 'dekhegi',
  'دیکھیں گے': 'dekheinge',
  
  'لکھے گا': 'likhega',
  'لکھے گی': 'likhegi',
  'لکھیں گے': 'likheinge',
  
  'پڑھے گا': 'parhega',
  'پڑھے گی': 'parhegi',
  'پڑھیں گے': 'parheinge',

  // ============================================
  // AUXILIARY VERBS (معاون افعال)
  // ============================================
  'ہے': 'hai',
  'ہیں': 'hain',
  'تھا': 'tha',
  'تھی': 'thi',
  'تھے': 'the',
  'تھیں': 'thin',
  'ہوں': 'hoon',
  'ہو': 'ho',
  'ہوں گے': 'hongay',
  'ہو گا': 'hoga',
  'ہو گی': 'hogii',
  'ہوں گی': 'hongi',
  'ہوتا': 'hota',
  'ہوتی': 'hoti',
  'ہوتے': 'hote',
  'ہوئی': 'hoi',
  'ہوئے': 'hoe',

  // ============================================
  // PARTICLES & CONJUNCTIONS (حروف)
  // ============================================
  'کہ': 'keh',
  'تو': 'to',
  'بھی': 'bhi',
  'ہی': 'hi',
  'سے': 'se',
  'پر': 'par',
  'پہ': 'pe',
  'میں': 'mein',
  'کو': 'ko',
  'کا': 'ka',
  'کی': 'ki',
  'کے': 'ke',
  'لیے': 'liye',
  'تک': 'tak',
  'اور': 'aur',
  'یا': 'ya',
  'نہیں': 'nahin',
  'نہ': 'na',
  'مگر': 'magar',
  'لیکن': 'lekin',
  'کیوں': 'kyun',
  'کیا': 'kya',
  'کیسے': 'kaise',
  'کب': 'kab',
  'کہاں': 'kahan',
  'جہاں': 'jahan',
  'وہاں': 'wahan',
  'یہاں': 'yahan',
  'اس لیے': 'is liye',
  'جب': 'jab',
  'تب': 'tab',
  'اگر': 'agar',
  'تو': 'to',
  'ورنہ': 'warna',
  'چونکہ': 'chonkeh',
  'باوجود': 'bawajood',
  'بغیر': 'baghair',
  'مت': 'mat',
  'ہرگز': 'hargiz',
  'ہمیشہ': 'hamesha',
  'کبھی': 'kabhi',
  'کبھی کبھی': 'kabhi kabhi',
  'اکثر': 'aksar',
  'بعض': 'baaz',
  'زیادہ': 'zyada',
  'تھوڑا': 'thora',
  'بہت': 'bohat',
  'انتہائی': 'intehai',
  'بالکل': 'bilkul',

  // ============================================
  // NOUNS - Common (اسم عام)
  // ============================================
  'انسان': 'insaan',
  'آدمی': 'aadmi',
  'عورت': 'aurat',
  'بچہ': 'bacha',
  'بچی': 'bachi',
  'لڑکا': 'larka',
  'لڑکی': 'larki',
  'مرد': 'mard',
  'خاتون': 'khatoon',
  'خاندان': 'khandaan',
  'گھر': 'ghar',
  'مکان': 'makaan',
  'دفتر': 'daftar',
  'اسکول': 'school',
  'کالج': 'college',
  'یونیورسٹی': 'university',
  'کتاب': 'kitaab',
  'قلم': 'qalam',
  'کاغذ': 'kaghaz',
  'میز': 'maez',
  'کرسی': 'kursi',
  'درخت': 'darakht',
  'پھول': 'phool',
  'پانی': 'paani',
  'ہوا': 'hawa',
  'آگ': 'aag',
  'مٹی': 'mitti',
  'پتھر': 'pathar',
  'آسمان': 'aasman',
  'زمین': 'zameen',
  'سمندر': 'samandar',
  'پہاڑ': 'pahaar',
  'جنگل': 'jangal',
  'شہر': 'sheher',
  'گاؤں': 'gaon',
  'ملک': 'mulk',
  'دیس': 'des',
  'وطن': 'watan',
  'قوم': 'qaum',
  'معاشرہ': 'mashrah',
  'ثقافت': 'saqafat',
  'تاریخ': 'tareekh',
  'زبان': 'zaban',
  'ادب': 'adab',
  'شاعری': 'shairi',
  'نظم': 'nazm',
  'غزل': 'ghazal',
  'مرثیہ': 'marsiya',
  'نوحہ': 'noha',
  'سلام': 'salam',
  'منقبت': 'manqabat',
  'حمد': 'hamd',
  'نعت': 'naat',

  // ============================================
  // POETRY WORDS - Love & Romance (عشق و محبت)
  // ============================================
  'عشق': 'ishq',
  'محبت': 'mohabbat',
  'پیار': 'pyar',
  'دل': 'dil',
  'درد': 'dard',
  'غم': 'gham',
  'خوشی': 'khushi',
  'مسرت': 'musarrat',
  'وفا': 'wafa',
  'جفا': 'jafa',
  'سچ': 'sach',
  'جھوٹ': 'jhooth',
  'وصل': 'wasl',
  'فراق': 'firaq',
  'ہجر': 'hijr',
  'ملن': 'milan',
  'راز': 'raaz',
  'بھید': 'bhed',
  'آرزو': 'aarzoo',
  'تمنا': 'tamanna',
  'خواہش': 'khwahish',
  'آہ': 'aah',
  'سسکی': 'siski',
  'آنکھ': 'aankh',
  'نظر': 'nazar',
  'چہرہ': 'chehra',
  'رخ': 'rukh',
  'لب': 'labb',
  'ہونٹ': 'hont',
  'زلف': 'zulf',
  'بال': 'baal',
  'گال': 'gaal',
  'پلک': 'palk',
  'ابرو': 'abru',
  'جادو': 'jaadu',
  'سحر': 'sehr',
  'نشہ': 'nasha',
  'خمار': 'khumar',
  'دیوانہ': 'deewana',
  'مجنوں': 'majnu',
  'فرہاد': 'farhad',
  'شیریں': 'sheereen',
  'لیلی': 'laila',
  'قیس': 'qais',
  'رنج': 'ranj',
  'الم': 'alam',
  'بے قراری': 'beqarari',
  'اضطراب': 'iztiraab',
  'بے چینی': 'bechaini',

  // ============================================
  // POETRY WORDS - Nature (فطرت)
  // ============================================
  'چاند': 'chaand',
  'سورج': 'suraj',
  'ستارہ': 'sitarah',
  'تارہ': 'tarah',
  'مہتاب': 'mahtab',
  'آفتاب': 'aaftab',
  'قوس قزح': 'qous-e-quzah',
  'بادل': 'baadal',
  'برسات': 'barsaat',
  'بارش': 'baarish',
  'بوند': 'boond',
  'پھوار': 'phuwar',
  'قطرہ': 'qatra',
  'ندیدہ': 'nadeeda',
  'صبح': 'subah',
  'سویرا': 'sawera',
  'شام': 'shaam',
  'سنجھ': 'sanjh',
  'رات': 'raat',
  'تاریکی': 'tareeki',
  'اندھیرا': 'andhera',
  'اجالا': 'ujala',
  'روشنی': 'roshni',
  'چمک': 'chamak',
  'بہار': 'bahaar',
  'خزاں': 'khizan',
  'گرمی': 'garmi',
  'سردی': 'sardi',
  'موسم': 'mausam',
  'ہوا': 'hawa',
  'جھونکا': 'jhonka',
  'آندھی': 'aandhi',
  'طوفان': 'toofan',
  'سمند': 'samand',
  'دریا': 'dariya',
  'ندی': 'nadi',
  'جھیل': 'jheel',
  'چشمہ': 'chashma',
  'کنواں': 'kuwan',
  'باغ': 'baagh',
  'چمن': 'chaman',
  'گلشن': 'gulshan',
  'پھلواری': 'phulwari',
  'سبزہ': 'sabza',
  'گھاس': 'ghaas',
  'پتہ': 'patta',
  'شاخ': 'shaakh',
  'ٹہنی': 'tehni',
  'پھل': 'phal',
  'بیج': 'beej',
  'پرندہ': 'parinda',
  'بلبل': 'bulbul',
  'قمری': 'qamri',
  'کوکل': 'kokil',
  'طوطا': 'tota',
  'مور': 'mor',
  'شاہین': 'shaheen',
  'عقاب': 'uqaab',
  'گلاب': 'gulaab',
  'چنبیلی': 'chanbeli',
  'چمیلی': 'chameli',
  'موتیا': 'motia',
  'کیوڑہ': 'kewra',
  'یاسمین': 'yasmeen',

  // ============================================
  // POETRY WORDS - Philosophical (فلسفہ)
  // ============================================
  'زندگی': 'zindagi',
  'موت': 'maut',
  'مرگ': 'marg',
  'حیات': 'hayat',
  'وفات': 'wafaat',
  'دنیا': 'duniya',
  'جہاں': 'jahan',
  'عالم': 'aalam',
  'کائنات': 'kaainaat',
  'وجود': 'wujood',
  'عدم': 'adam',
  'ہستی': 'hasti',
  'فنا': 'fana',
  'بقا': 'baqa',
  'روح': 'rooh',
  'جان': 'jaan',
  'نفس': 'nafs',
  'دماغ': 'dimagh',
  'عقل': 'aql',
  'دل': 'dil',
  'قلب': 'qalb',
  'جگر': 'jigar',
  'سینہ': 'seenah',
  'خودی': 'khudi',
  'انانیت': 'ananiat',
  'خدا': 'khuda',
  'رب': 'rabb',
  'پروردگار': 'parwardigar',
  'مالک': 'malik',
  'حقیقت': 'haqeeqat',
  'واقعیت': 'waqeat',
  'خیال': 'khayal',
  'تصور': 'tasawwur',
  'انداز': 'andaaz',
  'طور': 'tour',
  'طرح': 'tarah',
  'قسمت': 'qismat',
  'تقدیر': 'taqdeer',
  'نصیب': 'naseeb',
  'بخت': 'bakht',
  'اقبال': 'iqbal',

  // ============================================
  // GHALIB SPECIFIC WORDS
  // ============================================
  'نکتہ': 'nuqtah',
  'بیان': 'bayan',
  'تلخی': 'talkhi',
  'مے': 'mai',
  'ساقی': 'saqi',
  'مے خانہ': 'mai-khana',
  'بوتل': 'botal',
  'جام': 'jaam',
  'پیمانہ': 'peymana',
  'سبو': 'subo',
  'مستی': 'masti',
  'مے پرستی': 'mai-parasti',
  'بے خودی': 'bekhudi',
  'سرمستی': 'sarmasti',
  'غمِ دل': 'gham-e-dil',
  'رازِ دل': 'raaz-e-dil',
  'آہِ دل': 'aah-e-dil',
  'نالہ': 'nalah',
  'فریاد': 'faryaad',
  'شکایت': 'shikayat',
  'گلہ': 'gilah',
  'اشک': 'ashk',
  'آنسو': 'aansu',
  'خونِ جگر': 'khoon-e-jigar',
  'داغ': 'daagh',
  'نقش': 'naqsh',
  'خاک': 'khaak',
  'گرد': 'gard',
  'غبار': 'ghubaar',
  'ذرا': 'zara',
  'کچھ': 'kuch',
  'کوئی': 'koi',
  'کسی': 'kisi',
  'جسے': 'jisey',
  'اسے': 'usey',
  'انہیں': 'unhein',

  // ============================================
  // IQBAL SPECIFIC WORDS
  // ============================================
  'خودی': 'khudi',
  'افلاک': 'aflaak',
  'ملت': 'millat',
  'مسلم': 'muslim',
  'قرآن': 'quran',
  'حدیث': 'hadees',
  'ذکر': 'zikr',
  'فکر': 'fikr',
  'جہاد': 'jihad',
  'شاہین': 'shaheen',
  'عقاب': 'uqaab',
  'باز': 'baaz',
  'پرواز': 'parwaaz',
  'بلندی': 'bulandi',
  'عروج': 'urooj',
  'زوال': 'zawaal',
  'افتاد': 'uftaad',
  'قامت': 'qamat',
  'ہمت': 'himmat',
  'جرات': 'juraat',
  'حوصلہ': 'hauslah',
  'ارادہ': 'iraadah',
  'عزم': 'azm',
  'تکیہ': 'takiyah',
  'سہارا': 'sahara',
  'سپنا': 'sapna',
  'خواب': 'khwab',
  'تعمیر': 'taameer',
  'تخریب': 'takhreeb',
  'اصلاح': 'islaah',
  'تبدیلی': 'tabdeeli',
  'انقلاب': 'inqilab',

  // ============================================
  // FAIZ SPECIFIC WORDS
  // ============================================
  'دست': 'dast',
  'ظلم': 'zulm',
  'جلاد': 'jallad',
  'زنداں': 'zindan',
  'زنجیر': 'zanjeer',
  'سولہ': 'solah',
  'جنوری': 'janvari',
  'لاہور': 'lahore',
  'وطن': 'watan',
  'غرض': 'gharz',
  'حوالات': 'hawalaat',
  'قید': 'qaid',
  'مکمل': 'mukammal',
  'نامکمل': 'namukammal',
  'ادھورا': 'adhoora',
  'پورا': 'poora',
  'سچا': 'sacha',
  'جھوٹا': 'jhoota',
  'بے وفا': 'bewafa',
  'سچا': 'sacha',
  'رستہ': 'rastah',
  'راستہ': 'raastah',
  'منزل': 'manzil',
  'مسافت': 'masafat',
  'دور': 'door',
  'قریب': 'qareeb',
  'پاس': 'paas',
  'سامنے': 'saamney',
  'پیچھے': 'peechay',
  'اوپر': 'oopar',
  'نیچے': 'neechey',
  'اندر': 'andar',
  'باہر': 'bahar',

  // ============================================
  // KARBALA / NOHA SPECIFIC WORDS
  // ============================================
  'کربلا': 'karbala',
  'حسین': 'hussain',
  'عباس': 'abbas',
  'زینب': 'zainab',
  'سکینہ': 'sakina',
  'امام': 'imaam',
  'شہید': 'shaheed',
  'پیاس': 'pyaas',
  'خون': 'khoon',
  'صبر': 'sabr',
  'علم': 'alam',
  'خیام': 'khayam',
  'فرات': 'furaat',
  'نہر': 'nehr',
  'لشکر': 'lashkar',
  'میدان': 'maidaan',
  'سرزمین': 'sarzameen',
  'تیر': 'teer',
  'تلوار': 'talwaar',
  'نیزہ': 'neezah',
  'خنجر': 'khanjar',
  'خیمہ': 'khaimah',
  'خیمے': 'khaimay',
  'شامیانہ': 'shamiyanah',
  'قافلہ': 'qaflah',
  'کارواں': 'karwaan',
  'شمر': 'shimr',
  'یزید': 'yazeed',
  'سجدہ': 'sajdah',
  'سجود': 'sujood',
  'عزاداری': 'azaadari',
  'سینہ زنی': 'seenah zani',
  'زنجیر زنی': 'zanjeer zani',
  'ماتم': 'maatam',
  'نوحہ': 'noha',
  'مرثیہ': 'marsiya',
  'سلام': 'salam',
  'زیارت': 'ziyarat',
  'مزار': 'mazaar',
  'روضہ': 'roza',
  'حرم': 'haram',
  'حرمین': 'haramain',
  
  // Karbala places
  'نجف': 'najaf',
  'کوفہ': 'kufa',
  'شام': 'shaam',
  'دمشق': 'damishq',
  'بغداد': 'baghdad',
  'ایران': 'iran',
  'مشرق': 'mashriq',
  'مغرب': 'maghrib',
  
  // Karbala personalities
  'حضرت': 'hazrat',
  'رسول': 'rasool',
  'محمد': 'muhammad',
  'علی': 'ali',
  'فاطمہ': 'fatima',
  'حسن': 'hassan',
  'زین العابدین': 'zain-ul-abideen',
  'باقر': 'baqir',
  'صادق': 'sadiq',
  'موسیٰ': 'musa',
  'رضا': 'raza',
  'تقی': 'taqi',
  'نقی': 'naqi',
  'عسکری': 'askari',
  'مہدی': 'mehdi',

  // ============================================
  // RELIGIOUS / ISLAMIC WORDS
  // ============================================
  'اللہ': 'allah',
  'رب': 'rabb',
  'خدا': 'khuda',
  'محمد': 'muhammad',
  'رسول': 'rasool',
  'نبی': 'nabi',
  'انبیاء': 'ambiya',
  'قرآن': 'quran',
  'حدیث': 'hadees',
  'سنت': 'sunnat',
  'نماز': 'namaz',
  'روزہ': 'roza',
  'حج': 'hajj',
  'زکوٰۃ': 'zakat',
  'مسجد': 'masjid',
  'مدرسہ': 'madrasah',
  'مولوی': 'molvi',
  'شیخ': 'sheikh',
  'پیر': 'peer',
  'مرشد': 'murshid',
  'توبہ': 'toubah',
  'استغفار': 'astaghfar',
  'دعا': 'dua',
  'مناجات': 'munajat',
  'ذکر': 'zikr',
  'فکر': 'fikr',
  'تصوف': 'tasawwuf',
  'طریقت': 'tareeqat',
  'شریعت': 'shariat',
  'حقیقت': 'haqeeqat',
  'معرفت': 'maarifat',
  'ولی': 'wali',
  'بزرگ': 'buzurg',
  'جنتی': 'jannati',
  'دوزخی': 'dozakhi',
  'جنت': 'jannat',
  'دوزخ': 'dozakh',
  'جہنم': 'jahannam',
  'فرشتہ': 'farishtah',
  'شیطان': 'shaitan',
  'ابلیس': 'iblees',
  'عیسیٰ': 'eesa',
  'موسیٰ': 'musa',
  'ابراہیم': 'ibrahim',
  'اسماعیل': 'ismail',
  'اسحاق': 'ishaq',
  'یعقوب': 'yaqoob',
  'یوسف': 'yousuf',
  'ایوب': 'ayyub',
  'یونس': 'younus',
  'داؤد': 'dawood',
  'سلیمان': 'suleman',

  // ============================================
  // ADJECTIVES (صفات)
  // ============================================
  'اچھا': 'acha',
  'برا': 'bura',
  'بڑا': 'bara',
  'چھوٹا': 'chota',
  'نया': 'naya',
  'پرانا': 'purana',
  'تازہ': 'tazah',
  'خوبصورت': 'khoobsurat',
  'بدصورت': 'badsoorat',
  'خوش': 'khush',
  'اداس': 'udaas',
  'غمگین': 'ghamgeen',
  'خوشگوار': 'khushgawar',
  'تلخ': 'talkh',
  'شیریں': 'sheereen',
  'گرم': 'garam',
  'ٹھنڈا': 'thanda',
  'گہرا': 'gehra',
  'اتھاہ': 'athah',
  'بلند': 'buland',
  'پست': 'past',
  'تیز': 'tez',
  'آہستہ': 'ahista',
  'روشن': 'roshan',
  'تاریک': 'tareek',
  'صاف': 'saaf',
  'گندا': 'ganda',
  'امیر': 'ameer',
  'غریب': 'ghareeb',
  'عظیم': 'azeem',
  'حقیر': 'haqeer',
  'مضبوط': 'mazboot',
  'کمزور': 'kamzor',
  'زندہ': 'zindah',
  'مردہ': 'murda',

  // ============================================
  // NUMBERS & QUANTITIES (اعداد)
  // ============================================
  'ایک': 'ek',
  'دو': 'do',
  'تین': 'teen',
  'چار': 'chaar',
  'پانچ': 'paanch',
  'چھ': 'chay',
  'سات': 'saat',
  'آٹھ': 'aath',
  'نو': 'nau',
  'دس': 'das',
  'گیارہ': 'gyarah',
  'بارہ': 'barah',
  'تیرہ': 'terah',
  'چودہ': 'chodah',
  'پندرہ': 'pandrah',
  'سولہ': 'solah',
  'سترہ': 'satrah',
  'اٹھارہ': 'atharah',
  'انیس': 'unees',
  'بیس': 'bees',
  'تیس': 'tees',
  'چالیس': 'chalees',
  'پچاس': 'pachaas',
  'ساٹھ': 'saath',
  'ستر': 'sattar',
  'اسی': 'assi',
  'نوے': 'nabbe',
  'سو': 'sau',
  'ہزار': 'hazaar',
  'لاکھ': 'laakh',
  'کروڑ': 'crore',
  'ارب': 'arab',
  'کھرب': 'kharab',
  'پہلا': 'pehla',
  'دوسرا': 'doosra',
  'تیسرا': 'teesra',
  'چوتھا': 'chotha',
  'پانچواں': 'panchwan',
  'چھٹا': 'chatta',
  'ساتواں': 'satwan',
  'آٹھواں': 'aathwan',
  'نواں': 'nawan',
  'دسواں': 'daswan',

  // ============================================
  // TIME WORDS (اوقات)
  // ============================================
  'آج': 'aaj',
  'کل': 'kal',
  'پرسوں': 'parson',
  'آئندہ': 'aindah',
  'گزشتہ': 'guzishtah',
  'اب': 'ab',
  'تب': 'tab',
  'پہلے': 'pehley',
  'بعد': 'baad',
  'دوران': 'doran',
  'صبح': 'subah',
  'دوپہر': 'dopehar',
  'شام': 'shaam',
  'رات': 'raat',
  'آدھی رات': 'aadhi raat',
  'پو پھٹتے': 'po phuttey',
  'طلوع': 'tuloo',
  'غروب': 'ghuroob',
  'گھنٹہ': 'ghanta',
  'منٹ': 'minute',
  'سیکنڈ': 'second',
  'دن': 'din',
  'ہفتہ': 'haftah',
  'مہینہ': 'maheenah',
  'سال': 'saal',
  'صدی': 'sadi',
  'ہزارہ': 'hazarah',
  
  // Days of week
  'پیر': 'peer',
  'منگل': 'mangal',
  'بدھ': 'budh',
  'جمعرات': 'jumerat',
  'جمعہ': 'jummah',
  'ہفتہ': 'haftah',
  'اتوار': 'itwar',

  // Months
  'جنوری': 'janvari',
  'فروری': 'farvari',
  'مارچ': 'march',
  'اپریل': 'aprail',
  'مئی': 'mai',
  'جون': 'june',
  'جولائی': 'julai',
  'اگست': 'agast',
  'ستمبر': 'sitamber',
  'اکتوبر': 'aktobar',
  'نومبر': 'navambar',
  'دسمبر': 'disambar',

  // ============================================
  // COMMON VERBS (اضافی افعال)
  // ============================================
  'چاہنا': 'chahna',
  'چاہتا': 'chata',
  'پسند': 'pasand',
  'کیا': 'kiya',
  'کر': 'kar',
  'کرکے': 'karke',
  'کرنا چاہیے': 'karna chahiye',
  'پڑنا': 'parna',
  'پڑتا': 'parta',
  'سکنا': 'sakna',
  'سکتا': 'sakta',
  'پانا': 'pana',
  'پاتا': 'pata',
  'رکھنا': 'rakhna',
  'رکھتا': 'rakhta',
  'دکھانا': 'dikhana',
  'دکھاتا': 'dikhata',
  'بتانا': 'batana',
  'بتاتا': 'batata',
  'سمجھنا': 'samajhna',
  'سمجھتا': 'samajhta',
  'بھولنا': 'bhoolna',
  'بھولتا': 'bhoolta',
  'یاد': 'yaad',
  'بھول': 'bhool',
  'سوچنا': 'sochna',
  'سوچتا': 'sochta',
  'فیصلہ': 'faisla',
  'کرنا': 'karna',

  // ============================================
  // EMOTIONS & FEELINGS (جذبات)
  // ============================================
  'خوشی': 'khushi',
  'غم': 'gham',
  'غصہ': 'ghussa',
  'پیار': 'pyar',
  'نفرت': 'nafrat',
  'ڈر': 'dar',
  'خوف': 'khauf',
  'امید': 'umeed',
  'مایوسی': 'mayoosi',
  'حسد': 'hasad',
  'حسد': 'hasad',
  'غیرت': 'ghairat',
  'شرم': 'sharm',
  'حیا': 'haya',
  'پشیمانی': 'pashimaani',
  'ندامت': 'nadamat',
  'افسوس': 'afsos',
  'رنج': 'ranj',
  'الم': 'alam',
  'بیقراری': 'beqarari',
  'اضطراب': 'iztiraab',
  'سکون': 'sukoon',
  'اطمینان': 'itminan',
  'چین': 'chain',
  'آرام': 'aaraam',
  'تکلیف': 'takleef',
  'آزمائش': 'aazmaish',
  'مشکل': 'mushkil',
  'آسانی': 'aasani',
  'خوبی': 'khoobi',
  'برائی': 'burai',

  // ============================================
  // BODY PARTS (اعضاء جسم)
  // ============================================
  'سر': 'sar',
  'چہرہ': 'chehra',
  'آنکھ': 'aankh',
  'ناک': 'naak',
  'کان': 'kaan',
  'منہ': 'munh',
  'دانت': 'daant',
  'زبان': 'zaban',
  'ہونٹ': 'hont',
  'گلا': 'gala',
  'گردن': 'gardan',
  'کندھا': 'kandha',
  'بازو': 'baazu',
  'ہاتھ': 'haath',
  'انگلی': 'ungli',
  'چھاتی': 'chati',
  'سینہ': 'seenah',
  'پیٹ': 'peyt',
  'کمر': 'kamar',
  'پیر': 'peer',
  'پاؤں': 'paaon',
  'ٹانگ': 'taang',
  'گھٹنا': 'ghutna',
  'جگر': 'jigar',
  'دل': 'dil',
  'دماغ': 'dimagh',
  'ریڑھ': 'reedh',
  'ہڈی': 'haddi',
  'پٹھا': 'patha',
  'خون': 'khoon',
  'رگ': 'rag',

  // ============================================
  // FAMILY RELATIONS (رشتے)
  // ============================================
  'ماں': 'maan',
  'والدہ': 'walida',
  'اماں': 'amma',
  'ابو': 'abbu',
  'والد': 'waalid',
  'باپ': 'baap',
  'بھائی': 'bhai',
  'بہن': 'behan',
  'بیٹا': 'beta',
  'بیٹی': 'beti',
  'شوہر': 'shohar',
  'بیوی': 'biwi',
  'دادا': 'dada',
  'دادی': 'dadi',
  'نانا': 'nana',
  'نانی': 'nani',
  'چچا': 'chacha',
  'چچی': 'chachi',
  'تایا': 'taya',
  'تائی': 'tai',
  'ماموں': 'mamoon',
  'مامی': 'mami',
  'خالو': 'khaloo',
  'خالہ': 'khala',
  'پھوپھی': 'phophi',
  'پھوپھا': 'phopha',
  'بھابی': 'bhabi',
  'بہنوئی': 'behnoi',
  'داماد': 'damad',
  'بہو': 'bahu',
  'نواسہ': 'nawasah',
  'نواسی': 'nawasi',
  'پوتا': 'pota',
  'پوتی': 'poti',

  // ============================================
  // PROFESSIONS (پیشے)
  // ============================================
  'ڈاکٹر': 'doctor',
  'انجینئر': 'engineer',
  'استاد': 'ustaad',
  'معلم': 'mualim',
  'طالب علم': 'talib-e-ilm',
  'وکیل': 'wakeel',
  'جج': 'judge',
  'پولیس': 'police',
  'فوجی': 'fouji',
  'سپاہی': 'sipahi',
  'کسان': 'kisaan',
  'مزدور': 'mazdoor',
  'تاجر': 'tajir',
  'بزنس مین': 'businessman',
  'نوکر': 'naukar',
  'مالک': 'malik',
  'ڈرائیور': 'driver',
  'پائلٹ': 'pilot',
  'بحری': 'behri',
  'دکاندار': 'dukandar',
  'قاضی': 'qazi',
  'مولوی': 'molvi',
  'خطیب': 'khatib',
  'واعظ': 'waiz',
  'شاعر': 'shair',
  'ادیب': 'adeeb',
  'مصور': 'musawwir',
  'موسیقار': 'moseeqar',
  'رقاص': 'raqaas',
  'تماشائی': 'tamashai',

  // ============================================
  // FOOD & DRINKS (کھانے پینے کی اشیاء)
  // ============================================
  'روٹی': 'roti',
  'نان': 'naan',
  'چاول': 'chawal',
  'دال': 'daal',
  'سبزی': 'sabzi',
  'گوشت': 'gosht',
  'مرغی': 'murghi',
  'مچھلی': 'machli',
  'انڈا': 'anda',
  'دودھ': 'doodh',
  'دہی': 'dahi',
  'پنیر': 'paneer',
  'گھی': 'ghee',
  'تیل': 'tel',
  'نمک': 'namak',
  'شکر': 'shakar',
  'چینی': 'chini',
  'چائے': 'chai',
  'قهوه': 'qahwa',
  'پانی': 'paani',
  'لیموں پانی': 'lemon paani',
  'شربت': 'sharbat',
  'ملک شیک': 'milkshake',
  'آئس کریم': 'ice cream',
  'حلوہ': 'halwa',
  'زردہ': 'zardah',
  'بریانی': 'biryani',
  'کباب': 'kabab',
  'قورمہ': 'qormah',
  'کراہی': 'karahi',
  'ہلیم': 'haleem',
  'نہاری': 'nihari',
  'پائے': 'paaye',
  'ساموسہ': 'samosah',
  'پکوڑے': 'pakoray',
  'چاٹ': 'chaat',
  'گول گپے': 'gol gappay',

  // ============================================
  // COLORS (رنگ)
  // ============================================
  'سفید': 'safed',
  'کالا': 'kala',
  'سرخ': 'surkh',
  'لال': 'laal',
  'نیلا': 'neela',
  'ہرا': 'hara',
  'پیلا': 'peela',
  'نارنجی': 'narangi',
  'جامنی': 'jamni',
  'گلابی': 'gulabi',
  'بھورا': 'bhoora',
  'سنہری': 'sunhari',
  'چاندی': 'chaandi',
  'فیروزی': 'firozi',
  'خاکی': 'khaaki',
  'نیا': 'neya',
  'بیگن': 'begun',
  'آسمانی': 'aasmaani',
  'زیتونی': 'zaitooni',
  'ریتلا': 'retla',

  // ============================================
  // DIRECTIONS & PLACES (سمتیں اور مقامات)
  // ============================================
  'شمال': 'shumal',
  'جنوب': 'junoob',
  'مشرق': 'mashriq',
  'مغرب': 'maghrib',
  'اوپر': 'oopar',
  'نیچے': 'neechey',
  'دائیں': 'daain',
  'بائیں': 'baain',
  'سامنے': 'saamney',
  'پیچھے': 'peechay',
  'اندر': 'andar',
  'باہر': 'bahar',
  'قریب': 'qareeb',
  'دور': 'door',
  'پاس': 'paas',
  'اس پار': 'us paar',
  'اس طرف': 'us taraf',
  'اس جانب': 'us jaanib',
  'مرکز': 'markaz',
  'کنارہ': 'kinaarah',
  'نقطہ': 'nuqtah',
  'حدود': 'hudood',

  // ============================================
  // WEATHER & CLIMATE (موسم)
  // ============================================
  'بارش': 'baarish',
  'برف': 'barf',
  'دھوپ': 'dhoop',
  'چھاؤں': 'chhaaon',
  'بادل': 'baadal',
  'آندھی': 'aandhi',
  'طوفان': 'toofan',
  'گرمی': 'garmi',
  'سردی': 'sardi',
  'خنکی': 'khanki',
  'نمی': 'nami',
  'دھند': 'dhund',
  'کہر': 'kohar',
  'اولے': 'olay',
  'ژالہ باری': 'zhalah baari',
  'بجلی': 'bijli',
  'کڑک': 'karak',
  'قوس قزح': 'qous-e-quzah',
  'مطلع': 'matla',
  'فضا': 'fiza',

  // ============================================
  // COMMON HOUSEHOLD ITEMS (گھریلو اشیاء)
  // ============================================
  'میز': 'maez',
  'کرسی': 'kursi',
  'الماری': 'almaari',
  'بستر': 'bistar',
  'تکیہ': 'takiyah',
  'گدّا': 'gadda',
  'قالین': 'qaleen',
  'پردہ': 'pardah',
  'چراغ': 'chiraagh',
  'لیمپ': 'lamp',
  'پنکھا': 'pankha',
  'کولر': 'cooler',
  'اے سی': 'AC',
  'فریج': 'fridge',
  'چولہا': 'chulha',
  'برتن': 'bartann',
  'پلیٹ': 'plate',
  'چمچ': 'chammach',
  'کانٹا': 'kaanta',
  'چھری': 'chhuri',
  'گلاس': 'glass',
  'کپ': 'cup',
  'ٹی وی': 'TV',
  'کمپیوٹر': 'computer',
  'موبائل': 'mobile',
  'فون': 'phone',
  'گھڑی': 'ghari',
  'رسی': 'rassi',
  'کینچی': 'kainchi',
  'سوئی': 'sui',
  'دھاگہ': 'dhaghah',
  'بٹن': 'button',
  'زپ': 'zip',
  'جوتا': 'joota',
  'سلیپر': 'sleeper',
  'کرتا': 'karta',
  'شرٹ': 'shirt',
  'پتلون': 'pantaloon',
  'پاجامہ': 'pajamah',
  'چادر': 'chadar',

  // ============================================
  // ADDITIONAL POETRY WORDS
  // ============================================
  'نغمہ': 'naghma',
  'ترانہ': 'tarana',
  'سرود': 'surood',
  'گیت': 'geet',
  'گانا': 'gana',
  'رقص': 'raqs',
  'موسیقی': 'moseeqi',
  'سُر': 'sur',
  'تال': 'taal',
  'لے': 'lay',
  'وزن': 'wazan',
  'بحر': 'bahr',
  'قافیہ': 'qafiyah',
  'ردیف': 'radeef',
  'مطلع': 'matla',
  'مقطع': 'maqta',
  'تشبیہ': 'tashbeeh',
  'استعارہ': 'istearah',
  'کنایہ': 'kinayah',
  'تجنیس': 'tajnees',
  'تضاد': 'tazaad',
  'مراعات': 'muraat',
  'تلمیح': 'talmee',
  'حسن': 'husn',
  'جمال': 'jamaal',
  'جلال': 'jalaal',
  'کمال': 'kamaal',
  'فضل': 'fazl',
  'کرم': 'karam',
  'بخشش': 'bakhshish',
  'رحم': 'rehm',
  'غصہ': 'ghussa',
  'قہر': 'qahr',
  'عذاب': 'azaab',
  'ثواب': 'sawaab',
  'جنت': 'jannat',
  'دوزخ': 'dozakh',
};

// ============================================
// MULTI-WORD PHRASES
// ============================================
export const multiWordPhrases = {
  // Future tense
  'دیکھیں گے': 'dekheinge',
  'دیکھیں گے': 'dekheinge',
  'کریں گے': 'kareinge',
  'جائیں گے': 'jayeinge',
  'آئیں گے': 'aayeinge',
  'رہیں گے': 'raheinge',
  'پائیں گے': 'payeinge',
  'کھائیں گے': 'khayeinge',
  'سوئیں گے': 'soyeinge',
  'روئیں گے': 'royeinge',
  
  // Past tense with particles
  'کیا تھا': 'kiya tha',
  'کیا تھی': 'kiya thi',
  'کیا تھے': 'kiya thay',
  'گیا تھا': 'gaya tha',
  'گئی تھی': 'gayi thi',
  'گئے تھے': 'gaye thay',
  
  // Present continuous
  'رہا ہے': 'raha hai',
  'رہی ہے': 'rahi hai',
  'رہے ہیں': 'rahe hain',
  'رہا ہوں': 'raha hoon',
  'رہی ہوں': 'rahi hoon',
  'رہے ہو': 'rahe ho',
  
  // Common phrases
  'نہیں ہے': 'nahin hai',
  'نہیں تھا': 'nahin tha',
  'نہیں تھی': 'nahin thi',
  'نہیں تھے': 'nahin thay',
  'جا رہا': 'ja raha',
  'جا رہی': 'ja rahi',
  'جا رہے': 'ja rahe',
  'آ رہا': 'aa raha',
  'آ رہی': 'aa rahi',
  'آ رہے': 'aa rahe',
  'کر رہا': 'kar raha',
  'کر رہی': 'kar rahi',
  'کر رہے': 'kar rahe',
  'دیکھ رہا': 'dekh raha',
  'دیکھ رہی': 'dekh rahi',
  'دیکھ رہے': 'dekh rahe',
  
  // Poetry phrases
  'دل سے': 'dil se',
  'دل میں': 'dil mein',
  'دل کا': 'dil ka',
  'دل کی': 'dil ki',
  'دل کو': 'dil ko',
  'جان سے': 'jaan se',
  'جان میں': 'jaan mein',
  'جان کا': 'jaan ka',
  'جان کی': 'jaan ki',
  'آنکھوں میں': 'aankhon mein',
  'آنکھوں سے': 'aankhon se',
  'ہاتھوں میں': 'haathon mein',
  'پاؤں تلے': 'paaon taley',
  'سر پر': 'sar par',
  'دل و جاں': 'dil-o-jaan',
  'خون و جگر': 'khoon-o-jigar',
  'خونِ دل': 'khoon-e-dil',
  'خونِ جگر': 'khoon-e-jigar',
  'آہِ دل': 'aah-e-dil',
  'نالہِ دل': 'nalah-e-dil',
  'غمِ دل': 'gham-e-dil',
  'رازِ دل': 'raaz-e-dil',
};

// ============================================
// NASAL FORMS (Words ending with ں)
// ============================================
export const nasalForms = {
  'ہوں': 'hoon',
  'ہیں': 'hain',
  'تھیں': 'thin',
  'لکھیں': 'likhein',
  'پڑھیں': 'parhein',
  'دیکھیں': 'dekhein',
  'کریں': 'karein',
  'جائیں': 'jayein',
  'آئیں': 'aayein',
  'کہیں': 'kahein',
  'سنئیں': 'sunein',
  'رہیں': 'rahein',
  'پائیں': 'payein',
  'کھائیں': 'khayein',
  'سوئیں': 'soyein',
  'روئیں': 'royein',
  'ہوں گے': 'hongay',
  'ہوں گی': 'hongi',
  'لکھیں گے': 'likheinge',
  'پڑھیں گے': 'parheinge',
  'دیکھیں گے': 'dekheinge',
  'کریں گے': 'kareinge',
  'جائیں گے': 'jayeinge',
  'آئیں گے': 'aayeinge',
};

export default { urduCorpus, multiWordPhrases, nasalForms };